CREATE TABLE GOODS (
    ID_GOODS CHAR(10) PRIMARY KEY,
    NOMENCLATURE CHAR(20),
    MEASURE CHAR(10)
);

CREATE TABLE WAREHOUSE (
    ID_WH CHAR(10) PRIMARY KEY,
    NAME CHAR(20),
    TOWN CHAR(20)
);

CREATE TABLE AGENT (
    ID_AG CHAR(10) PRIMARY KEY,
    NAME_AG CHAR(20),
    TOWN CHAR(20),
    PHONE CHAR(10)
);

CREATE TABLE GOODS_WH (
    ID SERIAL PRIMARY KEY,
    ID_WH CHAR(10) REFERENCES WAREHOUSE(ID_WH),
    ID_GOODS CHAR(10) REFERENCES GOODS(ID_GOODS),
    QUANTITY NUMERIC(15,2)
);

CREATE TABLE OPERATION (
    ID SERIAL PRIMARY KEY,
    ID_GOODS CHAR(10) REFERENCES GOODS(ID_GOODS),
    ID_AG CHAR(10) REFERENCES AGENT(ID_AG),
    ID_WH CHAR(10) REFERENCES WAREHOUSE(ID_WH),
    TYPEOP CHAR(1),
    QUANTITY NUMERIC(15,2),
    PRICE NUMERIC(15,2),
    OP_DATE DATE
);
